### ISSUE TITLE
this "https://rapidapi.com/justin-WFnsXH_t6/api/exercisedb/pricing" is 404

### ISSUE THREAD

**Issue by yong-asial** [juan-serrano-soria/workout-app#15]
https://rapidapi.com/justin-WFnsXH_t6/api/exercisedb/pricing

![Screenshot 2024-02-19 at 17 34 10](https://github.com/juan-serrano-soria/workout-app/assets/28589278/0997cc13-f79e-4bca-8e8a-5a0f56b2a9f2)

**Comment by yong-asial** [comment]
maybe this page https://rapidapi.com/products/pricing/?

**Comment by juan-serrano-soria** [comment]
Apparently the API I used is only visible if logged into RapidAPI...
But the pricing is different for each API, so I can point this out in the guide, first create account and then go to the ExerciseDB pricing page.

**Comment by juan-serrano-soria** [comment]
API has become private, new users can not access it. Exposing already existent API key in the repo.
