### ISSUE TITLE
Error when navigate to Dashboard

### ISSUE THREAD

**Issue by yong-asial** [juan-serrano-soria/workout-app#17]
![Screenshot 2024-02-19 at 17 50 50](https://github.com/juan-serrano-soria/workout-app/assets/28589278/1b237a54-b8d7-45fc-a7b1-2503e1cb4255)

**Comment by juan-serrano-soria** [comment]
Did you manually navigate to localhost:8080/dashboard without logging in to get this error?
Looks like the app does not have user information in state (has not logged in) and that's why it is breaking.
Since the normal workflow is to open login page and then go from there, it should not break.
