### ISSUE TITLE
Search exercise not working sometimes

### ISSUE THREAD

**Issue by yong-asial** [juan-serrano-soria/workout-app#21]
when i first test it, it is working ...

then i tried the 2nd time, it got following error

![Screenshot 2024-02-21 at 17 05 54](https://github.com/juan-serrano-soria/workout-app/assets/28589278/fe82e183-be3d-4e98-9a70-9d99a0562bcd)

**Comment by yong-asial** [comment]
I think maybe it's due to the API is not stable?  i'm not sure tho.

**Comment by juan-serrano-soria** [comment]
API usage limit has been reached I think :(
Although I should display an error instead of letting the app break

**Comment by juan-serrano-soria** [comment]
Firs account I created to get an API Key was on January 26th, so maybe we can wait for the monthly limit to reset.

**Comment by juan-serrano-soria** [comment]
Error screen added to let the user know API usage has been reached. 
Since this issue is about searching exercises not working, operation has been confirmed, API returns error message about monthly limit usage.
The problem now is that the app depends on this API.
