### ISSUE TITLE
Search Exercise Throws error

### ISSUE THREAD

**Issue by yong-asial** [juan-serrano-soria/workout-app#5]
![Screenshot 2024-02-09 at 18 12 14](https://github.com/juan-serrano-soria/workout-app/assets/28589278/d0232603-39bc-4714-8dc4-0fdff4c79949)

![Screenshot 2024-02-09 at 18 14 03](https://github.com/juan-serrano-soria/workout-app/assets/28589278/f2ada297-910c-471b-b02d-130712addc31)

**Comment by juan-serrano-soria** [comment]
This problem is caused because latest API key was not uploaded. Either way it will be solved when fix for #12 is implemented. Thanks! 🙇
